version: "3.1"
services:

    postgres:
      image: mdillon/postgis:11-alpine
      container_name: mapa-violencia-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=mapa

    webserver:
      image: nginx:alpine
      container_name: mapa-violencia-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    php-fpm:
      build: docker/php-fpm
      container_name: mapa-violencia-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini


# version: '3' 
# services:
#     app: 
#         image: php:7.3-fpm
#         build: images/php/
#         working_dir: /var/www/html
#         volumes:
#             - ./:/var/www/html
#         ports:
#             - "9000:9000"
#         command: 
#             - 
    
#     # nginx:
#     #     image: nginx:1.15
#     #     volumes:
#     #         - "./:/var/www/html"
#     #         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     #     ports:
#     #         - "80:80"
#     #     depends_on:
#     #         - app