version: "3.1"
services:

    database:
      image: mdillon/postgis:11-alpine
      container_name: database
      working_dir: /application
      ports:
        - "5432:5432"
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=mapa

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8888:80"

    app:
      build: docker/php-fpm
      container_name: app
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini